/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stockbarang;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Habibizaki
 */
public class stockbarang_form extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(stockbarang_form.class.getName());

    /**
     
     */
    public stockbarang_form() {
        initComponents();
        koneksi();
        loadSupplier();
        loadTable();
    }
    
    private void koneksi(){
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_toko_handphone",
                    "root", "");
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }
    
    private void loadSupplier(){
        try{
            supplier.removeAllItems();
            supplier.addItem("Pilih Supplier");
            
            String sql = "SELECT id_supplier, nama_supplier FROM supplier";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {
                supplier.addItem(rs.getString("id_supplier") + " - " + rs.getString("nama_supplier"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load supplier: " + e.getMessage());
        }
    }
    
    private void loadTable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Barang");
        model.addColumn("ID Supplier");
        model.addColumn("Nama Barang");
        model.addColumn("Merk");
        model.addColumn("Tipe");
        model.addColumn("Harga");
        model.addColumn("Stock");
        
        try{
            String sql = "SELECT * FROM stock_barang";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()){
                model.addRow (new Object[]{
                rs.getInt("id_barang"),
                rs.getInt("id_supplier"),
                rs.getString("nama_barang"),
                rs.getString("merk"),
                rs.getString("tipe"),
                rs.getString("harga"),
                rs.getString("stok")
            });
            }
            tabel.setModel(model);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }
    
    private void resetForm() {
        supplier.setSelectedIndex(0);
        barang.setText("");
        merk.setText("");
        tipe.setText("");
        harga.setText("");
        stock.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        barang = new javax.swing.JTextField();
        merk = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        kirim = new javax.swing.JButton();
        Text_Alamat = new javax.swing.JLabel();
        Text_Nomor = new javax.swing.JLabel();
        Text_Nama = new javax.swing.JLabel();
        Text_Judul = new javax.swing.JLabel();
        BTN_Kirim2 = new javax.swing.JButton();
        Text_Alamat1 = new javax.swing.JLabel();
        tipe = new javax.swing.JTextField();
        Text_Alamat2 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        Text_Alamat3 = new javax.swing.JLabel();
        supplier = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "ID Supplier", "Nama Barang", "Merk", "Tipe", "Harga", "Stock"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        hapus.setText("Hapus");
        hapus.addActionListener(this::hapusActionPerformed);

        edit.setText("Edit");
        edit.addActionListener(this::editActionPerformed);

        kirim.setText("Kirim");
        kirim.addActionListener(this::kirimActionPerformed);

        Text_Alamat.setText("Merk");

        Text_Nomor.setText("Nama Barang");

        Text_Nama.setText("Nama Supplier");

        Text_Judul.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        Text_Judul.setText("Formulir Stock Barang");

        BTN_Kirim2.setText("Halaman Utama");
        BTN_Kirim2.addActionListener(this::BTN_Kirim2ActionPerformed);

        Text_Alamat1.setText("Tipe");

        Text_Alamat2.setText("Harga");

        Text_Alamat3.setText("Stock");

        supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Supplier" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Text_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Text_Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Text_Nomor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Text_Alamat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Text_Alamat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Text_Alamat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(barang)
                                    .addComponent(merk, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(tipe, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(supplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 86, Short.MAX_VALUE)
                                .addComponent(kirim)
                                .addGap(18, 18, 18)
                                .addComponent(edit)
                                .addGap(18, 18, 18)
                                .addComponent(hapus)
                                .addGap(55, 55, 55))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Kirim2)
                        .addGap(123, 123, 123)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(Text_Judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(Text_Nama))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Text_Judul)
                                .addGap(46, 46, 46)
                                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Nomor)
                            .addComponent(barang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(merk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Alamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Alamat2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Alamat3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kirim)
                            .addComponent(edit)
                            .addComponent(hapus))
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Kirim2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
       int row = tabel.getSelectedRow();
       
       barang.setText(tabel.getValueAt(row, 2).toString());
       merk.setText(tabel.getValueAt(row, 3).toString());
       tipe.setText(tabel.getValueAt(row, 4).toString());
       harga.setText(tabel.getValueAt(row, 5).toString());
       stock.setText(tabel.getValueAt(row, 6).toString());
       
       String idSupplier = tabel.getValueAt(row, 1).toString();
       
       for (int i = 0; i < supplier.getItemCount(); i++) {
           if (supplier.getItemAt(i).toString().startsWith(idSupplier + " - ")) {
               supplier.setSelectedIndex(i);
               break;
           }
       }
    }//GEN-LAST:event_tabelMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       int row = tabel.getSelectedRow();
       
       if (row == -1) {
           JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
           return;
       }
       
       int confirm = JOptionPane.showConfirmDialog(this,
               "Yakin ingin menghapus data ini?",
               "Konfirmasi", JOptionPane.YES_NO_OPTION);
       if (confirm == JOptionPane.YES_OPTION) {
           try {
               String idBarang = tabel.getValueAt(row, 0).toString();
               
               String sql = "DELETE FROM stock_barang WHERE id_barang=?";
               pst = conn.prepareStatement(sql);
               pst.setString(1, idBarang);
               
               pst.executeUpdate();
               
               JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
               
               loadTable();
               resetForm();
           } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Gagal hapus data: " + e.getMessage());
       }
       }
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       int row = tabel.getSelectedRow();
       if (row == -1){
           JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!");
           return;
       }
       try {
           String idBarang = tabel.getValueAt(row, 0).toString();
           String selectedSupplier = supplier.getSelectedItem().toString();
           String idSupplier = selectedSupplier.split(" - ")[0];
           String sql = "UPDATE stock_barang SET "
                   + "id_supplier=?, nama_barang=?, merk=?, tipe=?, harga=?, stok=? "
                   + "WHERE id_barang=?";
           
           pst = conn.prepareStatement(sql);
           pst.setString(1, idSupplier);
           pst.setString(2, barang.getText());
           pst.setString(3, merk.getText());
           pst.setString(4, tipe.getText());
           pst.setString(5, harga.getText());
           pst.setString(6, stock.getText());
           pst.setString(7, idBarang);
           
           pst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Data berhasil diedit!");
           
           loadTable();
           resetForm();
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Gagal edit data: " + e.getMessage());
       }
    }//GEN-LAST:event_editActionPerformed

    private void kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimActionPerformed
       if (supplier.getSelectedIndex() == 0 || barang.getText().isEmpty() || merk.getText().isEmpty() || tipe.getText().isEmpty() || harga.getText().isEmpty() || stock.getText().isEmpty()) {
           JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
           return;
       }
       try{
           String selectedSupplier = supplier.getSelectedItem().toString();
           String idSupplier = selectedSupplier.split(" - ")[0];
           
           String sql = "INSERT INTO stock_barang " + "(id_supplier, nama_barang, merk, tipe, harga, stok) " + "VALUES (?, ?, ?, ?, ?, ?)";
           
           pst = conn.prepareStatement(sql);
           pst.setString(1, idSupplier);
           pst.setString(2, barang.getText());
           pst.setString(3, merk.getText());
           pst.setString(4, tipe.getText());
           pst.setString(5, harga.getText());
           pst.setString(6, stock.getText());
           
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(this, "Data stock barang berhasil disimpan!");
           
           loadTable();
           resetForm();
           
       } catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
       }
    }//GEN-LAST:event_kirimActionPerformed

    private void BTN_Kirim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Kirim2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_Kirim2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new stockbarang_form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Kirim2;
    private javax.swing.JLabel Text_Alamat;
    private javax.swing.JLabel Text_Alamat1;
    private javax.swing.JLabel Text_Alamat2;
    private javax.swing.JLabel Text_Alamat3;
    private javax.swing.JLabel Text_Judul;
    private javax.swing.JLabel Text_Nama;
    private javax.swing.JLabel Text_Nomor;
    private javax.swing.JTextField barang;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kirim;
    private javax.swing.JTextField merk;
    private javax.swing.JTextField stock;
    private javax.swing.JComboBox<String> supplier;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tipe;
    // End of variables declaration//GEN-END:variables
}
