/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supplier;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Koneksi.koneksi;

/**
 *
 * @author HYPE
 */
public class supplier_Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(supplier_Form.class.getName());

    /**
     * Creates new form supplier_Form
     */
    public supplier_Form() {
        initComponents();
        TampilData();
        
        Tabel_Informasi.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_InformasiMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Judul = new javax.swing.JLabel();
        Text_Nama = new javax.swing.JLabel();
        Text_Nomor = new javax.swing.JLabel();
        Text_Alamat = new javax.swing.JLabel();
        Form_Nama = new javax.swing.JTextField();
        Form_Nomor = new javax.swing.JTextField();
        Form_Alamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Informasi = new javax.swing.JTable();
        BTN_Kirim = new javax.swing.JButton();
        BTN_Edit = new javax.swing.JButton();
        BTN_Hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text_Judul.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        Text_Judul.setText("Formulir Supplier");

        Text_Nama.setText("Nama Supplier");

        Text_Nomor.setText("Nomor Telepon");

        Text_Alamat.setText("Alamat");

        Form_Nama.addActionListener(this::Form_NamaActionPerformed);

        Tabel_Informasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Suplier", "Nama Supplier", "Nomor Telepon", "Alamat"
            }
        ));
        Tabel_Informasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_InformasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Informasi);

        BTN_Kirim.setText("Kirim");
        BTN_Kirim.addActionListener(this::BTN_KirimActionPerformed);

        BTN_Edit.setText("Edit");
        BTN_Edit.addActionListener(this::BTN_EditActionPerformed);

        BTN_Hapus.setText("Hapus");
        BTN_Hapus.addActionListener(this::BTN_HapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addComponent(BTN_Kirim)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Edit)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Hapus)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Text_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Text_Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Text_Nomor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Form_Nama)
                            .addComponent(Form_Nomor)
                            .addComponent(Form_Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(Text_Judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Text_Nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Nomor)
                            .addComponent(Form_Nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Form_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_Kirim)
                            .addComponent(BTN_Edit)
                            .addComponent(BTN_Hapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Text_Judul)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Form_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Form_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Form_NamaActionPerformed

    private void BTN_KirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KirimActionPerformed
           // 1. Validasi Input: Mencegah data kosong masuk ke database
            if (Form_Nama.getText().trim().isEmpty() || 
                Form_Nomor.getText().trim().isEmpty() || 
                Form_Alamat.getText().trim().isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data (Nama, No Telp, dan Alamat) terlebih dahulu!");
                return; // Menghentikan proses jika ada yang kosong
            }

            try {
                // 2. Memanggil koneksi database
                java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();

                // 3. Menyiapkan Query SQL (Tanpa id_supplier karena AUTO_INCREMENT)
                String sql = "INSERT INTO supplier (nama_supplier, no_telp, alamat) VALUES (?, ?, ?)";

                // 4. Memasukkan teks dari form ke dalam parameter query (?)
                java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, Form_Nama.getText());
                pstmt.setString(2, Form_Nomor.getText());
                pstmt.setString(3, Form_Alamat.getText());

                // 5. Mengeksekusi query untuk menyimpan ke database
                pstmt.executeUpdate();

                // 6. Menampilkan pesan sukses
                javax.swing.JOptionPane.showMessageDialog(null, "Data Supplier Berhasil Disimpan!");

                // 7. Segarkan tampilan tabel agar data baru langsung muncul
                TampilData();

                // 8. Bersihkan kolom input setelah berhasil menyimpan
                Form_Nama.setText("");
                Form_Nomor.setText("");
                Form_Alamat.setText("");

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
            }
    }//GEN-LAST:event_BTN_KirimActionPerformed


    private void BTN_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HapusActionPerformed
        // 1. Cek apakah ada baris tabel yang dipilih
        int selectedRowIndex = Tabel_Informasi.getSelectedRow();

        if (selectedRowIndex < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan klik/pilih data pada tabel yang ingin dihapus terlebih dahulu!");
            return;
        }

        // 2. Ambil ID dan Nama Supplier untuk ditampilkan di pesan konfirmasi
        String idSupplier = Tabel_Informasi.getValueAt(selectedRowIndex, 0).toString();
        String namaSupplier = Tabel_Informasi.getValueAt(selectedRowIndex, 1).toString();

        // 3. Konfirmasi penghapusan
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus data supplier: " + namaSupplier + "?", 
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();

                // 4. Query DELETE berdasarkan id_supplier
                String sql = "DELETE FROM supplier WHERE id_supplier = ?";

                java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, idSupplier);

                pstmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");

                // 5. Refresh tabel dan bersihkan form
                TampilData();
                Form_Nama.setText("");
                Form_Nomor.setText("");
                Form_Alamat.setText("");

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BTN_HapusActionPerformed

    private void Tabel_InformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_InformasiMouseClicked
        // 1. Dapatkan baris nomor berapa yang sedang diklik oleh kursor
        int selectedRowIndex = Tabel_Informasi.getSelectedRow();

        // 2. Pastikan baris yang diklik valid (mencegah error jika salah klik area)
        if (selectedRowIndex >= 0) {
            // 3. Ambil 'model' dari tabel agar kita bisa membaca isi teks di dalamnya
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Tabel_Informasi.getModel();

            // 4. Tarik datanya dan lempar ke dalam JTextField form Anda.
            // PENTING: Sesuaikan nama 'formIdBarang', 'FormNamaBarang', dll dengan nama variabel JTextField Anda!

            // Mengambil data dari kolom pertama (index 0)
            Form_Nama.setText(model.getValueAt(selectedRowIndex, 1).toString());

            // Mengambil data dari kolom kedua (index 1), contohnya akan menarik teks seperti "All New Avanza"
            Form_Nomor.setText(model.getValueAt(selectedRowIndex, 2).toString()); 

            // Jika ada kolom tambahan, lanjutkan saja polanya:
            Form_Alamat.setText(model.getValueAt(selectedRowIndex, 3).toString());
        }
    }//GEN-LAST:event_Tabel_InformasiMouseClicked

    private void BTN_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EditActionPerformed
        // 1. Cek apakah ada baris tabel yang dipilih
        int selectedRowIndex = Tabel_Informasi.getSelectedRow();

        if (selectedRowIndex < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan klik/pilih data pada tabel yang ingin diubah terlebih dahulu!");
            return;
        }

        // 2. Ambil ID Supplier dari kolom pertama (index 0) pada baris yang dipilih
        String idSupplier = Tabel_Informasi.getValueAt(selectedRowIndex, 0).toString();

        // 3. Validasi agar form tidak dikosongkan saat mengedit
        if (Form_Nama.getText().trim().isEmpty() || 
            Form_Nomor.getText().trim().isEmpty() || 
            Form_Alamat.getText().trim().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "Semua data (Nama, No Telp, Alamat) tidak boleh kosong!");
            return;
        }

        // 4. Konfirmasi pengubahan data
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Yakin ingin mengubah data supplier ini?", "Konfirmasi Ubah",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = Koneksi.koneksi.ConnectionDB();

                // 5. Query UPDATE (id_supplier digunakan sebagai patokan di bagian WHERE)
                String sql = "UPDATE supplier SET nama_supplier = ?, no_telp = ?, alamat = ? WHERE id_supplier = ?";

                java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, Form_Nama.getText());
                pstmt.setString(2, Form_Nomor.getText());
                pstmt.setString(3, Form_Alamat.getText());
                pstmt.setString(4, idSupplier); // Memasukkan ID dari tabel

                pstmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");

                // 6. Refresh tabel dan bersihkan form
                TampilData();
                Form_Nama.setText("");
                Form_Nomor.setText("");
                Form_Alamat.setText("");

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BTN_EditActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new supplier_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Edit;
    private javax.swing.JButton BTN_Hapus;
    private javax.swing.JButton BTN_Kirim;
    private javax.swing.JTextField Form_Alamat;
    private javax.swing.JTextField Form_Nama;
    private javax.swing.JTextField Form_Nomor;
    private javax.swing.JTable Tabel_Informasi;
    private javax.swing.JLabel Text_Alamat;
    private javax.swing.JLabel Text_Judul;
    private javax.swing.JLabel Text_Nama;
    private javax.swing.JLabel Text_Nomor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void TampilData() {
      // 1. Membuat model untuk kolom tabel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Mengembalikan nilai false agar semua baris dan kolom terkunci
            return false;
        }
    };
        model.addColumn("ID Supplier"); 
        model.addColumn("Nama Supplier");
        model.addColumn("No Telepon");
        model.addColumn("Alamat");
        
        // 2. Memasukkan model ke variabel JTable Anda
        // PENTING: Ganti 'TabelSupplier' dengan nama variabel JTable Anda di NetBeans
        Tabel_Informasi.setModel(model);
        
        try {
        // 3. Memanggil koneksi (Pastikan nama class koneksi Anda sesuai)
        java.sql.Connection conn = Koneksi.koneksi.ConnectionDB(); 
        java.sql.Statement stat = conn.createStatement();

        // 4. Query untuk mengambil semua data dari tabel (Sesuaikan nama tabel Anda)
        String sql = "SELECT * FROM supplier"; 
        java.sql.ResultSet res = stat.executeQuery(sql);

        // 5. Looping untuk memasukkan data baris demi baris
        while (res.next()) {
            model.addRow(new Object[]{
                // Nama kolom dalam getString("") harus SAMA PERSIS dengan di database
                res.getString("id_supplier"), 
                res.getString("nama_supplier"),
                res.getString("no_telp"),
                res.getString("alamat")
            });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data: " + e.getMessage());
        }
    }
}
