/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author apple
 */
public class customer_form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(customer_form.class.getName());
    
    // Variabel untuk menyimpan ID customer yang di pilih dari tabel.
    private String selectedId = "";
    /**
     * Creates new form customer_form
     * @throws customer.SQLException
     */
    public customer_form() throws SQLException {
        initComponents();
        load_table();
    }
    
    // --- METHOD KONEKSI DATABASE ---
    private Connection getConnection() throws SQLException, java.sql.SQLException {
        String url = "jdbc:mysql://localhost:8889/db_toko_handphone"; 
        String user = "root"; // Sesuaikan dengan username database kamu (default XAMPP: root)
        String pass = "root";     // Sesuaikan dengan password database kamu (default XAMPP: kosong)
        return DriverManager.getConnection(url, user, pass);
    }
    // --- METHOD UNTUK MENAMPILKAN DATA KE JTABLE ---

    
    // --- METHOD UNTUK MENGOSONGKAN FORM ---
    private void clear_form() {
        Form_Nama.setText("");
        Form_Nomor.setText("");
        Form_Alamat.setText("");
        selectedId = ""; // Reset ID
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Nama = new javax.swing.JLabel();
        Text_Nomor = new javax.swing.JLabel();
        Text_Alamat = new javax.swing.JLabel();
        Form_Nama = new javax.swing.JTextField();
        Form_Nomor = new javax.swing.JTextField();
        Form_Alamat = new javax.swing.JTextField();
        BTN_Kirim = new javax.swing.JButton();
        BTN_Edit = new javax.swing.JButton();
        BTN_Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Informasi = new javax.swing.JTable();
        Text_Judul = new javax.swing.JLabel();
        Text_Judul1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Form_Nama.addActionListener(this::Form_NamaActionPerformed);

        BTN_Kirim.setText("Kirim");
        BTN_Kirim.addActionListener(this::BTN_KirimActionPerformed);

        BTN_Edit.setText("Edit");
        BTN_Edit.addActionListener(this::BTN_EditActionPerformed);

        BTN_Hapus.setText("Hapus");
        BTN_Hapus.addActionListener(this::BTN_HapusActionPerformed);

        Tabel_Informasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Customer", "Customer Name", "Phone Number", "Address"
            }
        ));
        Tabel_Informasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_InformasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Informasi);

        Text_Judul.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        Text_Judul.setText("Customer Form");

        Text_Judul1.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N

        jLabel1.setText("Customer Name");

        jLabel2.setText("Phone Number");

        jLabel3.setText("Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(Text_Judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Text_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text_Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text_Nomor, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_Judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Form_Nama)
                        .addComponent(Form_Nomor)
                        .addComponent(Form_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_Kirim)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Edit)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Hapus)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Text_Judul)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Text_Nama))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Form_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Text_Judul1)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Form_Nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Nomor)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Form_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_Kirim)
                            .addComponent(BTN_Edit)
                            .addComponent(BTN_Hapus))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Form_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Form_NamaActionPerformed

    private void BTN_KirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KirimActionPerformed
        // Aksi Insert Data (CREATE)
        try (Connection conn = getConnection();
             PreparedStatement pst = conn.prepareStatement("INSERT INTO customer (nama_customer, no_telp, alamat) VALUES (?, ?, ?)")) {
            
            pst.setString(1, Form_Nama.getText());
            pst.setString(2, Form_Nomor.getText());
            pst.setString(3, Form_Alamat.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Disimpan!");
            load_table();
            clear_form();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        } catch (java.sql.SQLException ex) {
            System.getLogger(customer_form.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_BTN_KirimActionPerformed

    private void BTN_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EditActionPerformed
        // Aksi Update Data (UPDATE)
        if (selectedId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data dari tabel terlebih dahulu!");
            return;
        }
        
        try (Connection conn = getConnection();
             PreparedStatement pst = conn.prepareStatement("UPDATE customer SET nama_customer=?, no_telp=?, alamat=? WHERE id_customer=?")) {
            
            pst.setString(1, Form_Nama.getText());
            pst.setString(2, Form_Nomor.getText());
            pst.setString(3, Form_Alamat.getText());
            pst.setString(4, selectedId);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Diubah!");
            load_table();
            clear_form();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
        } catch (java.sql.SQLException ex) {
            System.getLogger(customer_form.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_BTN_EditActionPerformed

    private void BTN_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HapusActionPerformed
        // Aksi Hapus Data (DELETE)
        if (selectedId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data dari tabel terlebih dahulu!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = getConnection();
                 PreparedStatement pst = conn.prepareStatement("DELETE FROM customer WHERE id_customer=?")) {
                
                pst.setString(1, selectedId);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Pelanggan Berhasil Dihapus!");
                load_table();
                clear_form();
                
            } catch (SQLException e) {
                // Menangkap pesan error jika ID customer sedang dipakai di tabel penjualan (ON DELETE RESTRICT)
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: Kemungkinan data ini sedang digunakan pada riwayat transaksi.\n" + e.getMessage());
            } catch (java.sql.SQLException ex) {
                System.getLogger(customer_form.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_BTN_HapusActionPerformed

    private void Tabel_InformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_InformasiMouseClicked
        // Menampilkan data ke textfield ketika baris di klik
        int baris = Tabel_Informasi.rowAtPoint(evt.getPoint());
        if (baris > -1) {
            selectedId = Tabel_Informasi.getValueAt(baris, 0).toString(); // Ambil ID yang tersembunyi/ditampilkan
            Form_Nama.setText(Tabel_Informasi.getValueAt(baris, 1) != null ? Tabel_Informasi.getValueAt(baris, 1).toString() : "");
            Form_Nomor.setText(Tabel_Informasi.getValueAt(baris, 2) != null ? Tabel_Informasi.getValueAt(baris, 2).toString() : "");
            Form_Alamat.setText(Tabel_Informasi.getValueAt(baris, 3) != null ? Tabel_Informasi.getValueAt(baris, 3).toString() : "");
        }
    }//GEN-LAST:event_Tabel_InformasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new customer_form().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(customer_form.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Edit;
    private javax.swing.JButton BTN_Hapus;
    private javax.swing.JButton BTN_Kirim;
    private javax.swing.JTextField Form_Alamat;
    private javax.swing.JTextField Form_Nama;
    private javax.swing.JTextField Form_Nomor;
    private javax.swing.JTable Tabel_Informasi;
    private javax.swing.JLabel Text_Alamat;
    private javax.swing.JLabel Text_Judul;
    private javax.swing.JLabel Text_Judul1;
    private javax.swing.JLabel Text_Nama;
    private javax.swing.JLabel Text_Nomor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void load_table() throws SQLException {
        // Membuat tampilan model tabel
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("ID Customer");
        model.addColumn("Customer Name");
        model.addColumn("Phone Number");
        model.addColumn("Address");
        
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery("SELECT * FROM customer")) {
            
            // Mengisi baris tabel dengan data dari database
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_customer"),
                    rs.getString("nama_customer"),
                    rs.getString("no_telp"),
                    rs.getString("alamat")
                });
            }
            Tabel_Informasi.setModel(model);
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
}
